apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-and-reader-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
        - name: reader
          image: reader:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
            
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE

          volumeMounts:
              - name: config-volume
                mountPath: /etc/config-volume
                readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: log-output-config
         
        
    