apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-and-reader-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
        - name: reader
          image: reader:latest
          imagePullPolicy: Never
         
          ports:
            - containerPort: 3000
    