apiVersion: ENC[AES256_GCM,data:0L0=,iv:M2d22tFS2oNEaiDXbkJOnCjmJE1l08RQS2HRB82niTU=,tag:1GY1zsVFfcYG5lDPOFDmYg==,type:str]
kind: ENC[AES256_GCM,data:obTdTg8O,iv:nR7jQfmsxne5s+OjMo3QvL5WgNdvOA2FHsrKz2E+YA4=,tag:FkHIR1hhoJsawOIAzcST/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wMAFak+dQ1XRmGa6htQ=,iv:bnft7Imnk7Hwt6lrqQ/VD3Ac08F8OA/1lfnt1akzbdk=,tag:QVrBT9Tj3GJfPNIyjIitrw==,type:str]
data:
    MESSAGE: ENC[AES256_GCM,data:2egdDbbf70s/MAVeiGvBY4HW64E=,iv:FV9l+eHZpOfCLZhoOvlXpvsXX5VPOSbKzH8G0ITGvyg=,tag:5+8AXmmi18cWNVegfJTL3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldEdpQVJDMXNnWlJWQVBr
            bWM1Z0gzaFhLL0toSlYvWFZleVVCalZNUEhNCjFXZlRxYTNhdHNLZ2U5SEVSVC9y
            blVFMnRId2x0VSt4ZE1BNGRRV0dMemcKLS0tIGVoY2RzVkRmMGEvQ2xEOWhNeTkr
            RjBiajZxSXRibmFxTUxpYldubDRhSk0KoewyrNPkH+BG5Ewi1gTPO4vHCgCSDtN2
            3xbrborOLyeOwPNod9EZlL0B3rdjr/XTq5Zza1ea1eUK4RaO+o0EzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1645fs0tw77rq97347vz2cxl4q6nl4nynwhncdrystqx44wgdkq8s4h3g92
    lastmodified: "2026-09-03T19:39:26Z"
    mac: ENC[AES256_GCM,data:3TeOONQONXR5V8zbAUCauCY/Qpn35/Ew7jdJ+M3U2xYbKBGZF5/EKjC9WwFo88Mvf1tEddNC5mAdPAeh4x88mg7QdSt4F6fWKVjHemUs8Z6Td5O9w0EF2vcsouxmLq7J+UCQ1G7T/ny2k+WkesYNjdFx2FEPZ2qK4KA7hCfa6vk=,iv:1Q7KZ7mJO/i/WC5yaHG6mRlBjXjRgwTs03wIttYQg+g=,tag:aBuDiefed88A/qznmalDzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
