apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-and-reader-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
        - name: reader
          image: reader:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/counter
          ports:
            - containerPort: 3000
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: pv-claim-for-logoutput-and-ping-pong