apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: project
data:
  TODO_FRONTEND_SERVICE_PORT: "3456"
  TODO_FRONTEND_PORT: "3001"
  TODO_BACKEND_SERVICE_PORT: "1234"
  TODO_BACKEND_PORT: "3002"
  RANDOM_IMAGE_URL: "https://loremflickr.com/1200/800"
  RANDOM_IMAGE_FILE_PATH: "/usr/src/app/counter/image.jpg"
  STALE_FLAG_FILE_PATH: "/usr/src/app/counter/image-stale-served"
  CORS_ORIGIN1: "http://localhost:8081"
  CORS_ORIGIN2: "http://localhost:8082"



  

