apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobwiki
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cronjobwiki
              image: europe-north1-docker.pkg.dev/dwk-gke-508706/dwk-repo/cronjobwiki:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: todo-config
              env:
                - name: BACKEND_URL
                  value: "http://todo-backend:1234/todo-backend/todos"