
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-volume-for-logoutput-and-ping-pong
          persistentVolumeClaim:
            claimName: pv-claim-for-logoutput-and-ping-pong
            
      containers:
        - name: pingpong
          image: icelyx/pingpong
          volumeMounts:
            - name: shared-volume-for-logoutput-and-ping-pong
              mountPath: /usr/src/app/counter
          ports:
            - containerPort: 8080

