
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv-for-logoutput-and-ping-pong
spec:
  storageClassName: pv-for-logoutput-and-ping-pong
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  hostPath:
    path: /tmp/kube
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k3d-k3s-default-server-0
            
    
